/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Floor2({ ...props }) {
  const group = useRef()
  const bakedTexture = useTexture('/textures/floor2.png')
  const { nodes, materials } = useGLTF('/models/floor2.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[10,10,10]}>
      <mesh geometry={nodes.Floor2_Scene.geometry}>
       <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Floor2_Bobber_1.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Floor2_Bobber_2.geometry}>
       <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Floor2_Black.geometry} material={nodes.Floor2_Black.material} />
      <mesh geometry={nodes.Floor2_MetalDark.geometry} material={nodes.Floor2_MetalDark.material} />
      {/* <mesh geometry={nodes.Floor2_Windows.geometry} material={nodes.Floor2_Windows.material} /> */}
      {/* <mesh geometry={nodes.Floor2_Clickable_BugLight.geometry} material={nodes.Floor2_Clickable_BugLight.material} />
      <mesh geometry={nodes.Floor2_Clickable_Moxie.geometry} material={nodes.Floor2_Clickable_Moxie.material} />
      <mesh geometry={nodes.Floor2_Clickable_Up.geometry} material={nodes.Floor2_Clickable_Up.material} />
      <mesh geometry={nodes.Floor2_Clickable_Down.geometry} material={nodes.Floor2_Clickable_Down.material} /> */}
    </group>
  )
}

useGLTF.preload('/models/floor2.glb')
