/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Floor3({ ...props }) {
  const group = useRef()
  const bakedTexture = useTexture('/textures/floor3.png')
  const { nodes, materials } = useGLTF('/models/floor3.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[10,10,10]}>
      <mesh geometry={nodes.Floor3_Scene.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Floor3_Black.geometry} material={nodes.Floor3_Black.material} />
      {/* <mesh geometry={nodes.Floor3_Windows.geometry} material={nodes.Floor3_Windows.material} /> */}
      {/* <mesh geometry={nodes.Floor3_Clickable_Home.geometry} material={nodes.Floor3_Clickable_Home.material} /> */}
      {/* <mesh geometry={nodes.Floor3_Clickable_BlueHaze.geometry} material={nodes.Floor3_Clickable_BlueHaze.material} /> */}
      {/* <mesh
        geometry={nodes.Floor3_Clickable_MixedMessages.geometry}
        material={nodes.Floor3_Clickable_MixedMessages.material}
      /> */}
      {/* <mesh geometry={nodes.Floor3_Clickable_Lombard.geometry} material={nodes.Floor3_Clickable_Lombard.material} /> */}
      {/* <mesh
        geometry={nodes.Floor3_Clickable_WorldsEdge.geometry}
        material={nodes.Floor3_Clickable_WorldsEdge.material}
      /> */}
      {/* <mesh
        geometry={nodes.Floor3_Clickable_Acomplices.geometry}
        material={nodes.Floor3_Clickable_Acomplices.material}
      /> */}
      {/* <mesh
        geometry={nodes.Floor3_Clickable_HiddenWorlds.geometry}
        material={nodes.Floor3_Clickable_HiddenWorlds.material}
      /> */}
      {/* <mesh
        geometry={nodes.Floor3_Clickable_Graduation.geometry}
        material={nodes.Floor3_Clickable_Graduation.material}
      /> */}
      <mesh geometry={nodes.Floor3_Black002.geometry} material={nodes.Floor3_Black002.material} />
      {/* <mesh geometry={nodes.Floor3_Clickable_Up.geometry} material={nodes.Floor3_Clickable_Up.material} /> */}
      {/* <mesh geometry={nodes.Floor3_Clickable_Down.geometry} material={nodes.Floor3_Clickable_Down.material} /> */}
    </group>
  )
}

useGLTF.preload('/models/floor3.glb')
