/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Floor3({ ...props }) {
  const group = useRef()
  const bakedTexture = useTexture('/textures/floor3.png')
  const { nodes, materials } = useGLTF('/models/floor3.glb')
  return (
    <group ref={group} {...props} dispose={null}  scale={[10,10,10]}>
      
      <mesh name="Floor3_Scene" geometry={nodes.Floor3_Scene.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>

      <mesh name="Floor3_Black" geometry={nodes.Floor3_Black.geometry} material={nodes.Floor3_Black.material} />

      {/* <mesh name="Floor3_Windows" geometry={nodes.Floor3_Windows.geometry} material={nodes.Floor3_Windows.material} /> */}

      <mesh
        name="Floor3_Clickable_Home"
        geometry={nodes.Floor3_Clickable_Home.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_BlueHaze"
        geometry={nodes.Floor3_Clickable_BlueHaze.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_MixedMessages"
        geometry={nodes.Floor3_Clickable_MixedMessages.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_Lombard"
        geometry={nodes.Floor3_Clickable_Lombard.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_WorldsEdge"
        geometry={nodes.Floor3_Clickable_WorldsEdge.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_Acomplices"
        geometry={nodes.Floor3_Clickable_Acomplices.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_HiddenWorlds"
        geometry={nodes.Floor3_Clickable_HiddenWorlds.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_Graduation"
        geometry={nodes.Floor3_Clickable_Graduation.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>
      
      <mesh
        name="Floor3_Black002"
        geometry={nodes.Floor3_Black002.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_Up"
        geometry={nodes.Floor3_Clickable_Up.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

      <mesh
        name="Floor3_Clickable_Down"
        geometry={nodes.Floor3_Clickable_Down.geometry}
        >
        <meshBasicMaterial transparent= {true} opacity= {0} color={0x73fa85} />
      </mesh>

    </group>
  )
}

useGLTF.preload('/models/floor3.glb')
