/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Roof({ ...props }) {
  const group = useRef()
  const bakedTexture = useTexture('/textures/roof.png')
  const { nodes, materials } = useGLTF('/models/roof.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[10,10,10]}>
      <mesh geometry={nodes.Roof_Scene.geometry} material={nodes.Roof_Scene.material}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Roof__Windows.geometry} material={nodes.Roof__Windows.material} />
      <mesh geometry={nodes.Roof_Clickable_Down.geometry} material={nodes.Roof_Clickable_Down.material} />
    </group>
  )
}

useGLTF.preload('/models/roof.glb')
